### ISSUE TITLE
Host Nextclade dataset reference trees at nextstrain.org/nextclade/*

### ISSUE THREAD

**Issue by victorlin** [nextstrain/nextstrain.org#1037]
_from @trvrb in https://github.com/nextstrain/nextstrain.org/issues/1033#issuecomment-2391923991_

> My desire would be for every nextclade dataset to be represented at `/nextclade`. Right now I find myself going to clades.nextstrain.org and picking a reference pathogen and example dataset if I want to see the nextclade reference tree for a particular nextclade dataset. I don't know how easy including an automated push to data.nextstrain.org as part of the release process for nextclade datasets would be. Having these pushed to data.nextstrain.org would have the added benefit of easily looking at past versions, eg https://nextstrain.org/nextclade/sars-cov-2@2024-01-01 cc @rneher and @corneliusroemer

## Tasks

- [ ] /pathogens: Find a better way to display the `SARS-CoV-2 (Nextclade)` tile which currently represents all of `nextstrain.org/nextclade/*`
- [ ] Add `nextstrain.org/nextclade/flu`
- [ ] Add `nextstrain.org/nextclade/mpox`
- [ ] TODO: add more Nextclade datasets

**Comment by victorlin** [comment]
This was discussed with @rneher on a call today. It should be doable after figuring out the process to keep things up to date.

@joverlee521 also mentioned a workaround of using `/fetch` with a GitHub URL, for example: https://nextstrain.org/fetch/raw.githubusercontent.com/nextstrain/nextclade_data/refs/heads/master/data/nextstrain/sars-cov-2/BA.2.86/tree.json

**Comment by rneher** [comment]
I think we have addressed this by adding direct links from the nextclade datasets to a view on nextstrain.org. This reduces the number of places these data lives and the need to keep things in sync.

**Comment by victorlin** [comment]
A few more follow-ups, maybe these can be separate issues:

- Are we keeping https://nextstrain.org/nextclade/sars-cov-2 as-is?
    - I was thinking to redirect to the direct link that Nextclade uses, but that seems to be dynamic ([e.g.](https://nextstrain.org/fetch/data.clades.nextstrain.org/v3/nextstrain/sars-cov-2/wuhan-hu-1/orfs/2024-10-17--16-48-48Z/tree.json)). If it's possible to redirect, maybe do so for other `nextstrain.org/nextclade/*` as well?
- Should we keep the **SARS-CoV-2 (Nextclade)** tile on nextstrain.org/pathogens?
- This seems blog-post-worthy!
