### ISSUE TITLE
Heroku-20 stack is deprecated

### ISSUE THREAD

**Issue by victorlin** [nextstrain/nextstrain.org#974]
From [nextstrain-server pipeline page](https://dashboard.heroku.com/pipelines/38f67fc7-d93c-40c6-a182-501da2f89d9d):

> You have **7 apps** in this pipeline that are using the Heroku-20 stack, which is deprecated. From **April 30th, 2025**, Heroku-20 will be end-of-life and no longer receive security updates. From **May 1st, 2025**, builds will be disabled. Please upgrade your apps to a newer Heroku stack. [ Visit here to learn more](https://help.heroku.com/NPN275RK/heroku-20-end-of-life-faq)

## Tasks

- [x] https://github.com/nextstrain/nextstrain.org/pull/984
- [x] Promote canary to production
    - I'll let it sit in canary until something else prompts promotion.
- [x] Check that new review apps are updated to use Heroku-22 stack

**Comment by victorlin** [comment]
I think this is as simple as replacing `heroku-20` with `heroku-22` in [scripts/heroku-build](https://github.com/nextstrain/nextstrain.org/blob/c3b3b0382392aba2525c33ad5ea317daf0644392/scripts/heroku-build) and making sure the review app builds properly.

**Comment by victorlin** [comment]
Actually, scripts/heroku-build is only used for canary deployments which are then promoted into production. I'm not sure where the review apps are getting `heroku-20` from since there is no [app.json](https://devcenter.heroku.com/articles/app-json-schema#stack) file in this repo. Maybe it's based on whatever is used in production. I'll bump to `heroku-22` first then check if new review apps are updated to use that as well.

**Comment by trvrb** [comment]
It looks like this was just the `nextstrain-dev` app at this moment.

<img width="1219" alt="Screenshot 2024-08-23 at 10 47 46 AM" src="https://github.com/user-attachments/assets/87a83f3c-ad81-4f2e-8ba4-543d4f8ad138">

I just upgraded this app in Heroku and it should be updated "on next deploy".

**Comment by victorlin** [comment]
Thanks! It looks like the new review apps are using heroku-22, presumably because that's what's used in production now. Closing this issue as resolved.
